/*export const FETCH_lOGIN_REQUEST = 'FETCH_lOGIN_REQUEST';
export const FETCH_lOGIN_SUCESS = 'FETCH_lOGIN_SUCESS';
export const FETCH_lOGIN_FAILURE = 'FETCH_lOGIN_FAILURE';*/

export const TRY_LOGIN = 'TRY_LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';