export const COSTUMERS_TRY_RESULTS = 'COSTUMERS_TRY_RESULTS';
export const COSTUMERS_SELECT = 'COSTUMERS_SELECT';
export const COSTUMERS_FETCH_RESULTS = 'COSTUMERS_FETCH_RESULTS';
export const COSTUMERS_FETCH_SUCESS = 'COSTUMERS_FETCH_SUCESS';
export const COSTUMERS_FETCH_FAILURE = 'COSTUMERS_FETCH_FAILURE';